=== Computer-engineering-FICT/Computer-engineering-FICT/VII семестр/КС - Комп'ютерні системи/Software/Eucalyptus - Version 1.10/Eucalyptus - Exe/config/schema/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name = "param">
		<xs:complexType>
			<xs:attribute name="key" type="xs:integer" use="required"/>
			<xs:attribute name="value" type="xs:string"  use="required"/>
			<xs:attribute name="description" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name = "eucalyptusConfig">
		<xs:complexType>
			<xs:sequence>
	            <xs:element ref="param" maxOccurs = "unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== Computer-engineering-FICT/Computer-engineering-FICT/VII семестр/КС - Комп'ютерні системи/Software/Eucalyptus - Version 1.10/Eucalyptus - Jar/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<eucalyptusConfig xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://eucalyptus.com config.xsd">
    <param key = "1" value = "config/schema" description = "Dir with schema files"/>
	<param key = "2" value = "config/languages" description = "Dir with languages files"/>
	<param key = "3" value = "language.xsd" description = "File with language schema"/>
	<param key = "4" value = "RUS" description = "Default language"/>
	<param key = "5" value = "config/themes" description = "Dir with theme files"/>
	<param key = "6" value = "theme.xsd" description = "File with theme schema"/>
	<param key = "7" value = "standard" description = "Default theme"/>
	<param key = "8" value = "Eucalyptus" description = "Title of the frame"/>
    <param key = "9" value = "images" description = "Dir with images"/>
	<param key = "10" value = "tree.gif" description = "Icon on frame title"/>
	<param key = "11" value = "27" description = "Radius of task node"/>
	<param key = "12" value = "14" description = "Size of font of task node"/>
	<param key = "13" value = "2" description = "Tasks to make '+' operation"/>
	<param key = "14" value = "3" description = "Tasks to make '-' operation"/>
	<param key = "15" value = "4" description = "Tasks to make '*' operation"/>
	<param key = "16" value = "8" description = "Tasks to make '/' operation"/>
	<param key = "17" value = "edit_arrow.png" description = "Image for edit mode icon on tollbar"/>
	<param key = "18" value = "task.png" description = "Image for add tree_node mode icon on tollbar"/>
	<param key = "19" value = "task_connection.png" description = "Image for add connection icon on tollbar"/>
	<param key = "20" value = "add_cs_node.png" description = "Image for add cs_node mode icon on tollbar"/>
	<param key = "21" value = "cs_connection.png" description = "Image for add cs_node mode icon on tollbar"/>
	<param key = "22" value = "p" description = "Sign of procedure operation"/>
	<param key = "23" value = "5" description = "Radius of control node in connections"/>
	<param key = "24" value = "14" description = "Size of font of task connections"/>
	<param key = "25" value = "cs_node.png" description = "Image for cs_node"/>
	<param key = "26" value = "selected_cs_node.png" description = "Selected Image for cs_node"/>
    <param key = "27" value = "14" description = "Size of font of cs node"/>
    <param key = "28" value = "24" description = "Radius of cs node"/>
    <param key = "29" value = "undo.png" description = "Undo mode icon on tollbar"/>
	<param key = "30" value = "redo.png" description = "Redo mode icon on tollbar"/>
	<param key = "31" value = "config.png" description = "Configuration icon on tollbar"/>
	<param key = "32" value = "immerce.png" description = "Immerce icon on tollbar"/>
	<param key = "33" value = "edit_mode.png" description = "Build mode icon on tollbar"/>
	<param key = "34" value = "false" description = "Fullscreen mode"/>
	<param key = "35" value = "topologies" description = "Topology save directory"/>
	<param key = "36" value = "calculator.png" description = "Image for calculator icon on toolbar"/>
	<param key = "37" value = "symbol.gif" description = "Image for calculator icon on toolbar"/>
	<param key = "38" value = "1.10" description = "Version of application"/>
	<param key = "39" value = "dmytro.ivanov@mail.ru &lt;br /&gt; kvangee@gmail.com" description = "mails"/>
</eucalyptusConfig>
